// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPLI1GPgQXOwbEHQS6ZJPCe4i1WkWdLo',
    appId: '1:829122082821:web:56a81dd012382be4f6c46c',
    messagingSenderId: '829122082821',
    projectId: 'signin-ui-yj',
    authDomain: 'signin-ui-yj.firebaseapp.com',
    storageBucket: 'signin-ui-yj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK5rytblehdXASVBv-9fT46eskfsrTttE',
    appId: '1:829122082821:android:d21a3968e28b5cc9f6c46c',
    messagingSenderId: '829122082821',
    projectId: 'signin-ui-yj',
    storageBucket: 'signin-ui-yj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_bYo9r4_xsjm0co5xf6g9un4k50G6FI',
    appId: '1:829122082821:ios:2d8254b12e7b1cd1f6c46c',
    messagingSenderId: '829122082821',
    projectId: 'signin-ui-yj',
    storageBucket: 'signin-ui-yj.appspot.com',
    iosClientId: '829122082821-qjevf5m6c36ie6ia259sitvhurq8ae3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterUiDesignCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_bYo9r4_xsjm0co5xf6g9un4k50G6FI',
    appId: '1:829122082821:ios:d3c9bd6366487b0df6c46c',
    messagingSenderId: '829122082821',
    projectId: 'signin-ui-yj',
    storageBucket: 'signin-ui-yj.appspot.com',
    iosClientId: '829122082821-9h78sgefr1erkib4h0imo95662c7907k.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterUiDesignCommunity.RunnerTests',
  );
}
